let times = [
  {nome:'Clube Athletico Paranaense', jogos: 0, pontos:0},
  {nome:'Atletico Goianiense', jogos: 0, pontos:0},
  {nome:'Atletico Mineiro', jogos: 0, pontos:0},
  {nome:'Bahia Esporte Clube', jogos: 0, pontos:0},
  {nome:'Botafogo Futebol e Regatas', jogos: 0, pontos:0},
  {nome:'Red Bull Bragantino', jogos: 0, pontos:0},
  {nome:'Criciuma Futebol Clube', jogos: 0, pontos:0},
  {nome:'Cruzeiro Esporte Clube', jogos: 0, pontos:0},
  {nome:'Cuiaba Esporte Clube', jogos: 0, pontos:0},
  {nome:'Clube de Regatas Flamengo', jogos: 0, pontos:0},
  {nome:'Fluminense Futebol Clube', jogos: 0, pontos:0},
  {nome:'Fortaleza Esporte Clube', jogos: 0, pontos:0},
  {nome:'Gremio Esporte Clube', jogos: 0, pontos:0},
  {nome:'Sociedade Esportiva Internacinal', jogos: 0, pontos:0},
  {nome:'Juventude Esporte Clube', jogos: 0, pontos:0},
  {nome:'Palmeiras Futebol Clube', jogos: 0, pontos:0},
  {nome:'São Paulo Futebol Clube', jogos: 0, pontos:0},
  {nome:'Clube Regatas Vasco da Gama', jogos: 0, pontos:0},
  {nome:'Vitória Esporte Clube', jogos: 0, pontos:0},
  {nome:'Sociedade Esportiva Corinthians Paulista', jogos: 0, pontos:0},
];
